jVi for NetBeans 7.0
====================

See `CHANGES <http://jvi.sourceforge.net/?CHANGES.html>`_ for per release
feature and fix information.

nbvi-1.3.1.beta5.zip
--------------------
Tested with *NetBeans 7.0RC1*.

nbvi-1.3.1.beta4.zip
--------------------
Tested with *NetBeans 7.0Beta2*.

NOTE: NB now has support for proper undo/redo granularity. No patch required.

