See `CHANGES <http://jvi.sourceforge.net/?CHANGES.html>`_ for per release
feature and fix information.

| **nbvi-1.4**
|   Recent additions are map-commands and horizontal-scroll-commands.
| 
| **nbvi-1.4.1**
|   some ^W split window, move window commands; see CHANGES
|   multi-char {lhs} map-commands with 'timeout' options

