See `CHANGES <http://jvi.sourceforge.net/?CHANGES.html>`_ for per release
feature and fix information and details.
In NetBeans, install "jVi for NB Update Center",
with Tools>Plugins>AvailablePlugins
(source: Plugin Portal, category: editing)

If needed, manually install a jVi update center into NetBeans with Plugins>Settings>Add, use the URL:

http://sourceforge.net/projects/jvi/files/jVi-for-NetBeans/NetBeans-11-and-later/UC/catalog.xml.gz

| **nbvi-1.6.2** :history cmd output is clickable
| **nbvi-1.6.1** Improve dark L&F and per project property compatibility/interoperability
|     - show all matches as you type; 'cursorinview' option
| **nbvi-1.6** NetBeans 11.0 and later
|     - :tabmove, :tabclose, :tabonly; vim-8.x tab command syntax/features
|     - search 'magic' options; \\v, \\m, \\M, \\V in patterns
|     - :history, 'history', history up/down arrows and matching
| **nbvi-1.5.4** :register command, mapping Shft-space, Ctrl-space
| **nbvi-1.5.3** fix for jdk8 JComboBox
| **nbvi-1.5.1**
|     - visual bell, smarter scrolling, :toggle [left|right|top|bottom]
| **nbvi-1.5.0** NetBeans 7.2 and later 
|     - folding - rework, add new commands: zc, zC, zo, zO, za, zA, zv. 'fdo' option.
| **nbvi-1.4.5** fix for 7.1.1; works with 7.0. In 7.1 ":tog[gle]" minimize/restore output window group
| **nbvi-1.4.3** try ":set all", other minor features and fixes
| **nbvi-1.4.2** ^W split, resize, move window commands
| **nbvi-1.4.1** multi-char {lhs} map-commands with 'timeout' options

