#!/usr/bin/bash

. VARS.sh

OUT=$UC_OUT

GUTS=$OUT/cat-guts
CATALOG=$OUT/catalog.xml

#JVI_MAIN=/a/src/jvi-dev/rel/nbvi-1.4/updates.xml 
#JVI_UC=/a/src/nbm/jvi.uc.nb70/build/updates.xml

JVI_MAIN=/a/src/jvi-dev/nbvi/build/updates/updates.xml 
JVI_UC=/a/src/nbm/jvi.uc.nb70ea/build/updates.xml

JVI_ADD="
    /a/src/nbm/editor.pin/build/updates.xml
    "


mkdir -p $OUT
python combine_uc.py $JVI_MAIN $JVI_UC $JVI_ADD $OUT

echo '<?xml version="1.0" encoding="UTF-8"?>' > $CATALOG
echo '<!DOCTYPE module_updates PUBLIC "-//NetBeans//DTD Autoupdate Catalog 2.6//EN" "http://www.netbeans.org/dtds/autoupdate-catalog-2_6.dtd">' >> $CATALOG

cat $GUTS >> $CATALOG
rm $GUTS

# keep both files around since there is an update center out there
# that references the non-gz version
gzip -9 -c $CATALOG > $CATALOG.gz

