#!/usr/bin/bash

. VARS.sh

OUT=$UC_OUT

GUTS=$OUT/cat-guts
CATALOG=$OUT/catalog.xml

F1=/a/src/jvi-dev/rel/nbvi-1.4/updates.xml 
#F1=/a/src/jvi-dev/nbvi/build/updates/updates.xml 
F2=/a/src/nbm/dummy-nbvi-suite/build/updates/updates.xml


mkdir -p $OUT
python combine_uc.py $F1 $F2 $OUT

echo '<?xml version="1.0" encoding="UTF-8"?>' > $CATALOG
echo '<!DOCTYPE module_updates PUBLIC "-//NetBeans//DTD Autoupdate Catalog 2.6//EN" "http://www.netbeans.org/dtds/autoupdate-catalog-2_6.dtd">' >> $CATALOG

cat $GUTS >> $CATALOG
rm $GUTS

